### ISSUE TITLE
ICQ: delegator_delegations_query failed `Invalid query result format: denom is empty`

### ISSUE THREAD

**Issue by tpkeeper** [neutron-org/neutron-sdk#157]
please read this: https://github.com/cosmos/cosmos-sdk/pull/12409

for cosmos-sdk version >= v0.47.0, the `BondDenom` has migrated,
but `new_register_delegator_delegations_query_msg` still query it from params, this can result in `StorageValue` null and the `Delegations` reconstruct from `StorageValue` failed.

**Comment by pr0n00gler** [comment]
Thanks, we will fix this asap

**Comment by tpkeeper** [comment]
Sorry, you seem to have solved this problem. I just saw the v47 related interface
